version: '3.7'

services:
  salesforce-postgres-sync:
    container_name: salesforce-postgres-sync
    # image: chrisleekr/salesforce-postgres-sync:latest
    build:
      context: ./
      target: dev-stage
      # target: production-stage
    networks:
      - internal
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secretp422
    depends_on:
      - test-redis

  postgres:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
