version: '3.7'

services:
  salesforce-postgres-sync:
    container_name: salesforce-postgres-sync
    # image: chrisleekr/salesforce-postgres-sync:latest
    build:
      context: ./
      # target: dev-stage
      target: production-stage
    networks:
      - internal
    env_file:
      - .env
    environment:
      - POSTGRES_READWRITE_HOST=host.docker.internal
      - POSTGRES_READONLY_HOST=host.docker.internal

networks:
  internal:
    driver: bridge
